<a href="https://colab.research.google.com/github/TurMod/Data-Science-HW/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

t1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(t1)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
import numpy as np

t2 = np.zeros((3, 3))
print(t2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np

t3 = np.random.randint(1, 10, size=(5, 5))
print(t3)

[[3 4 6 4 4]
 [5 5 5 9 5]
 [5 3 3 7 2]
 [9 2 1 5 6]
 [1 3 7 9 6]]


In [6]:
import numpy as np

t4 = np.random.random((4, 4))
print(t4)

[[0.57481574 0.19836852 0.82225605 0.80750201]
 [0.77817603 0.56669621 0.93505749 0.32274994]
 [0.11275184 0.25866714 0.34178917 0.77372733]
 [0.16944194 0.34277607 0.53175133 0.12542256]]


In [7]:
import numpy as np

t5_1 = np.random.randint(1, 10, 5)
t5_2 = np.random.randint(1, 10, 5)
print(t5_1 + t5_2)
print(t5_1 - t5_2)
print(t5_1 * t5_2)

[ 7 10  7  4  9]
[-3  8 -5 -2 -1]
[10  9  6  3 20]


In [8]:
import numpy as np

t6_1 = np.array([1, 2, 3, 4, 5, 6 ,7], dtype=int)
t6_2 = np.array([8, 9, 10, 11, 12, 13, 14], dtype=int)
print(np.dot(t6_1, t6_2))

336


In [9]:
import numpy as np

t7_1 = np.random.randint(1, 10, (2, 2))
t7_2 = np.random.randint(1, 10, (2, 3))
print(np.dot(t7_1, t7_2))

[[  9  25   6]
 [ 37 137  32]]


In [10]:
import numpy as np

t8 = np.linalg.inv(np.random.randint(1, 10, (3, 3)))
print(t8)

[[ -2.66666667 -13.33333333   4.33333333]
 [  3.          16.          -5.        ]
 [ -0.66666667  -4.33333333   1.33333333]]


In [11]:
import numpy as np

t9 = np.random.random((4, 4)).T
print(t9)

[[0.57751049 0.28933509 0.61885009 0.57492875]
 [0.60083839 0.38070101 0.1563425  0.68101493]
 [0.83451059 0.53258835 0.64951619 0.40223337]
 [0.03828915 0.48893345 0.13007267 0.23783092]]


In [12]:
import numpy as np

t10_1 = np.random.randint(1, 10, (3, 4))
t10_2 = np.random.randint(1, 10, 4)
print(t10_1 * t10_2)

[[14 10 10 14]
 [ 4 16 30 56]
 [18  4 35 42]]


In [13]:
import numpy as np

t11_1 = np.random.random((2, 3))
t11_2 = np.random.random(3)
print(t11_1 * t11_2)

[[0.20438475 0.11755653 0.54334034]
 [0.67373157 0.2102147  0.55121672]]


In [14]:
import numpy as np

t12_1 = np.random.randint(1, 10, (2, 2))
t12_2 = np.random.randint(1, 10, (2, 2))
print(t12_1 * t12_2)

[[56 30]
 [ 5  8]]


In [15]:
import numpy as np

t13_1 = np.random.randint(1, 10, (2, 2))
t13_2 = np.random.randint(1, 10, (2, 2))
print(np.dot(t13_1, t13_2))

[[25 12]
 [96 54]]


In [16]:
import numpy as np

t14 = np.random.randint(1, 100, (5, 5)).sum()
print(t14)

1201


In [17]:
import numpy as np

t15_1 = np.random.randint(1, 10, (4, 4))
t15_2 = np.random.randint(1, 10, (4, 4))
print(t15_1 - t15_2)

[[ 7 -2  1  2]
 [-2 -2  0  0]
 [-1  6 -4  6]
 [ 1 -6 -3 -4]]


In [18]:
import numpy as np

t16 = np.random.random((3, 3)).sum(axis=1)
print(t16)

[1.15682729 1.91291186 1.81698984]


In [19]:
import numpy as np

t17_1 = np.random.randint(1, 10, (3, 4))
t17_2 = t17_1 ** 2
print(t17_1)
print(t17_2)

[[7 3 7 8]
 [2 8 9 3]
 [3 2 2 9]]
[[49  9 49 64]
 [ 4 64 81  9]
 [ 9  4  4 81]]


In [20]:
import numpy as np

t18 = np.random.randint(1, 50, 4)
print(np.sqrt(t18))

[4.89897949 2.23606798 4.89897949 4.35889894]
