<a href="https://colab.research.google.com/github/TurMod/Data-Science-HW/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

t1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(t1)

t2 = np.zeros((3, 3))
print(t2)

t3 = np.random.randint(1, 10, size=(5, 5))
print(t3)

t4 = np.random.random((4, 4))
print(t4)

t5_1 = np.random.randint(1, 10, 5)
t5_2 = np.random.randint(1, 10, 5)
print(t5_1 + t5_2)
print(t5_1 - t5_2)
print(t5_1 * t5_2)

t6_1 = np.array([1, 2, 3, 4, 5, 6 ,7], dtype=int)
t6_2 = np.array([8, 9, 10, 11, 12, 13, 14], dtype=int)
print(np.dot(t6_1, t6_2))

t7_1 = np.random.randint(1, 10, (2, 2))
t7_2 = np.random.randint(1, 10, (2, 3))
print(np.dot(t7_1, t7_2))

t8 = np.linalg.inv(np.random.randint(1, 10, (3, 3)))
print(t8)

t9 = np.random.random((4, 4)).T
print(t9)

t10_1 = np.random.randint(1, 10, (3, 4))
t10_2 = np.random.randint(1, 10, 4)
print(t10_1 * t10_2)

t11_1 = np.random.random((2, 3))
t11_2 = np.random.random(3)
print(t11_1 * t11_2)

t12_1 = np.random.randint(1, 10, (2, 2))
t12_2 = np.random.randint(1, 10, (2, 2))
print(t12_1 * t12_2)

t13_1 = np.random.randint(1, 10, (2, 2))
t13_2 = np.random.randint(1, 10, (2, 2))
print(np.dot(t13_1, t13_2))

t14 = np.random.randint(1, 100, (5, 5)).sum()
print(t14)

t15_1 = np.random.randint(1, 10, (4, 4))
t15_2 = np.random.randint(1, 10, (4, 4))
print(t15_1 - t15_2)

t16 = np.random.random((3, 3)).sum(axis=1)
print(t16)

t17_1 = np.random.randint(1, 10, (3, 4))
t17_2 = t17_1 ** 2
print(t17_1)
print(t17_2)

t18 = np.random.randint(1, 50, 4)
print(np.sqrt(t18))

[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 5 9 1 1]
 [5 9 4 3 5]
 [6 5 1 5 4]
 [7 1 5 6 8]
 [8 2 7 7 3]]
[[0.54686798 0.1971937  0.03750381 0.14178605]
 [0.80623647 0.68412918 0.81493051 0.84440122]
 [0.25753004 0.21366762 0.66698188 0.27157485]
 [0.39577014 0.06948464 0.86011651 0.51707272]]
[ 6 12  4  8  5]
[ 4  0  2 -2 -1]
[ 5 36  3 15  6]
336
[[18 20 10]
 [53 55 28]]
[[ 0.14814815 -0.01234568 -0.12345679]
 [ 0.03703704 -0.08641975  0.13580247]
 [-0.31481481  0.40123457  0.01234568]]
[[0.29300732 0.12764846 0.63136892 0.00688049]
 [0.36494393 0.89275483 0.20734484 0.95487423]
 [0.40253368 0.44044566 0.19558689 0.31141363]
 [0.78476339 0.92428483 0.82220873 0.45577836]]
[[20 56 28 48]
 [30 24 63 36]
 [30  8 35 36]]
[[0.18834411 0.14869272 0.51978049]
 [0.28773638 0.05213714 0.3843618 ]]
[[ 3 42]
 [18 12]]
[[51 26]
 [42 22]]
1374
[[ 0  2 -4 -2]
 [ 5 -6  3 -6]
 [ 3 -6 -6 -7]
 [ 0  1  0  3]]
[1.54551351 2.14742428 2.63232494]
[[5 9 3 8]
 [5 4 3 2]
 [3 9 3 8