<a href="https://colab.research.google.com/github/TurMod/Data-Science-HW/blob/main/Hw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([
    [2, 2],
    [2, 3],
    [2, 4],
    [5, 1],
    [5, 2]
])

y = np.dot(X, np.array([2, 3])) + 3

reggresor = LinearRegression().fit(X, y)

print(reggresor.predict(np.array([[5, 4]])))

[25.]


In [5]:
def linear_regression_loss(X, y, model):
  y_pred = model.predict(X)
  error = y_pred - y
  loss = np.mean(error**2)

  return loss

loss = linear_regression_loss(X, y, reggresor)
print(loss)

0.0


In [16]:
def gradient_descent_step(X, y, model, learning_rate):
  y_pred = model.predict(X)
  grad = 2/len(y) * X.T @ (y_pred - y)
  model.coef_ = model.coef_ - learning_rate * grad

  return model

reggresor = gradient_descent_step(X, y, reggresor, 0.01)

In [21]:
import pandas as pd

data = pd.read_csv('Housing.csv')
x = data[['area', 'bedrooms', 'bathrooms']].values
y = data['price'].values

reggresor_v2 = LinearRegression().fit(x, y)
print(reggresor_v2.coef_)

[3.78762754e+02 4.06820034e+05 1.38604950e+06]


In [22]:
X_trans = x.T
X_trans_X = X_trans @ x
X_trans_X_inv = np.linalg.inv(X_trans_X)
w_opt = X_trans_X_inv @ X_trans @ y
print(w_opt)

[3.72448352e+02 3.68974672e+05 1.37031315e+06]


In [23]:
reggresor_v2.coef_ == w_opt

array([False, False, False])